apiVersion: v1
kind: Service
metadata:
  name: windchill
  labels:
    app: windchill-nodeport
spec:
  type: NodePort
  ports:
    - nodePort: 30000
      port: 4005
      protocol: TCP
      targetPort: 4005
  selector:
    app: windchill